export default {
    ls: "List the files in the current directory",
    cd: "Change the current directory",
    cat: "Print the contents of a file",
    pwd: "Print the current working directory",
    version: "Print the terminal version",
    contact: "How to contact me",
    ps: "List the current running processes",
    kill: "Terminate a process by PID",
    ping: "Ping a server to see if it is reachable",
    clear: "Clear the terminal screen",
    wipe: "Remove all your history of command lines",
    history: "Show previously entered commands",
    whoami: "Print the current login name",
    who: "Show who is logged in",
    logout: "Log out and return to the login prompt",
    exit: "Exit the session (same as logout)",
    sudo: "Attempt to run a command as root",
    "party.sh": "Start a colorful party (from ~/tools)",
};
