name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v5

      - name: Build and publish website Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.TOKEN }}
          image-name: website
          extract-git-tag: true
          dockerfile: Dockerfile

      - name: Build and publish term SSH Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.TOKEN }}
          image-name: term
          extract-git-tag: true
          dockerfile: services/ssh/Dockerfile
